### PR TITLE
revert synopsys-detect 7.9.0 upgrade

### PR DESCRIPTION
**Pull request by dasormeter**

### CODE REVIEW

**Review by kareem-DA — APPROVED** [review]
LGTM

**Review by nycnewman — APPROVED** [review]
LGTM

**Comment by dasormeter** [comment]
revert successfully tested with daml repo -- gonna leave this branch open and flip daml repo to use this branch, but other projects can still keep going with new version that way

**Comment by dasormeter** [comment]
daml repo is now back up to `master` so this revert is no longer needed -- closing 

```
ci/cron/daily-compat.yml
379:          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
400:          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
418:          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
439:          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
458:          bash <(curl -s https://raw.githubusercontent.com/DACH-NY/security-blackduck/master/synopsys-detect) \
```

**Pull request closed without merging**
